FROM gcr.io/distroless/static
LABEL Brayden Winterton <brayden_winterton@byu.edu>
LABEL org.opencontainers.image.source https://github.com/byuoitav/atlona-switcher-microservice/

ARG NAME

COPY ${NAME} /app

ENTRYPOINT ["/app"]
